# CMake generated Testfile for 
# Source directory: D:/tinydbms/tinydbms/tests
# Build directory: D:/tinydbms/tinydbms/build-real/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test("tinydbms.storage_v1_stress" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.storage_v1_stress_test.exe")
set_tests_properties("tinydbms.storage_v1_stress" PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;7;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.storage_v1_metadata" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.storage_v1_metadata_test.exe")
set_tests_properties("tinydbms.storage_v1_metadata" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;7;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.storage_crud" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.storage_crud_test.exe")
set_tests_properties("tinydbms.storage_crud" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;14;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.heap_delete" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.heap_delete_test.exe")
set_tests_properties("tinydbms.heap_delete" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;19;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.heap_scan" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.heap_scan_test.exe")
set_tests_properties("tinydbms.heap_scan" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;24;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.scan_page" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.scan_page_test.exe")
set_tests_properties("tinydbms.scan_page" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;29;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.heap_table" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.heap_table_test.exe")
set_tests_properties("tinydbms.heap_table" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;34;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.page_allocation_state" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.page_allocation_state_test.exe")
set_tests_properties("tinydbms.page_allocation_state" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;39;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.buffer_pool" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.buffer_pool_test.exe")
set_tests_properties("tinydbms.buffer_pool" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;44;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.buffer_pool_flush" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.buffer_pool_flush_test.exe")
set_tests_properties("tinydbms.buffer_pool_flush" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;49;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.buffer_pool_concurrency" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.buffer_pool_concurrency_test.exe")
set_tests_properties("tinydbms.buffer_pool_concurrency" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;54;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.buffer_pool_loading" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.buffer_pool_concurrency_test.exe")
set_tests_properties("tinydbms.buffer_pool_loading" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;55;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.buffer_pool_clean_victim" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.buffer_pool_concurrency_test.exe")
set_tests_properties("tinydbms.buffer_pool_clean_victim" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;56;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.buffer_pool_dirty_victim" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.buffer_pool_dirty_victim_test.exe")
set_tests_properties("tinydbms.buffer_pool_dirty_victim" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;61;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.buffer_pool_prefetch" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.buffer_pool_prefetch_test.exe")
set_tests_properties("tinydbms.buffer_pool_prefetch" PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;66;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.buffer_pool_fifo" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.buffer_pool_fifo_test.exe")
set_tests_properties("tinydbms.buffer_pool_fifo" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;72;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.storage_buffer_pool" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.storage_buffer_pool_test.exe")
set_tests_properties("tinydbms.storage_buffer_pool" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;77;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.lifecycle" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.lifecycle_test.exe")
set_tests_properties("tinydbms.lifecycle" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;89;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.core_execution" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.core_execution_test.exe")
set_tests_properties("tinydbms.core_execution" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;97;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.storage_contract" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.storage_contract_test.exe")
set_tests_properties("tinydbms.storage_contract" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;110;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.page_file" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.page_file_test.exe")
set_tests_properties("tinydbms.page_file" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;125;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.page_file_concurrency" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.page_file_concurrency_test.exe")
set_tests_properties("tinydbms.page_file_concurrency" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;133;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.file_manager" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.file_manager_test.exe")
set_tests_properties("tinydbms.file_manager" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;145;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.file_manager_concurrency" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.file_manager_concurrency_test.exe")
set_tests_properties("tinydbms.file_manager_concurrency" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;153;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.storage_page_file_integration" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.storage_page_file_integration_test.exe")
set_tests_properties("tinydbms.storage_page_file_integration" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;167;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.system_catalog" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.system_catalog_test.exe")
set_tests_properties("tinydbms.system_catalog" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;175;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.system_catalog_failure" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.system_catalog_failure_test.exe")
set_tests_properties("tinydbms.system_catalog_failure" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;180;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.system_catalog_protection" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.system_catalog_protection_test.exe")
set_tests_properties("tinydbms.system_catalog_protection" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;191;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.record_codec" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.record_codec_test.exe")
set_tests_properties("tinydbms.record_codec" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;205;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.slotted_page" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.slotted_page_test.exe")
set_tests_properties("tinydbms.slotted_page" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;220;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.record_page" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.record_page_test.exe")
set_tests_properties("tinydbms.record_page" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;228;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.record_page_file_integration" "D:/tinydbms/tinydbms/build-real/tests/tinydbms.record_page_file_integration_test.exe")
set_tests_properties("tinydbms.record_page_file_integration" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;233;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.version" "D:/tinydbms/tinydbms/build-real/src/app/tinydbms.exe" "--version")
set_tests_properties("tinydbms.version" PROPERTIES  PASS_REGULAR_EXPRESSION [[tinydbms 0\.1\.0]] _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;235;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.contracts_compile" "D:/tinydbms/tinydbms/build-real/tests/tinydbms_contracts_compile_test.exe")
set_tests_properties("tinydbms.contracts_compile" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;250;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.core_lifecycle" "D:/tinydbms/tinydbms/build-real/tests/tinydbms_core_lifecycle_test.exe")
set_tests_properties("tinydbms.core_lifecycle" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;267;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.core_executor" "D:/tinydbms/tinydbms/build-real/tests/tinydbms_core_executor_test.exe")
set_tests_properties("tinydbms.core_executor" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;284;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.app_cli" "D:/tinydbms/tinydbms/build-real/tests/tinydbms_app_cli_test.exe")
set_tests_properties("tinydbms.app_cli" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;300;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.compiler_core_cli_integration" "D:/tinydbms/tinydbms/build-real/tests/tinydbms_compiler_core_cli_integration_test.exe")
set_tests_properties("tinydbms.compiler_core_cli_integration" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;323;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.real_modules_integration" "D:/tinydbms/tinydbms/build-real/tests/tinydbms_real_modules_integration_test.exe")
set_tests_properties("tinydbms.real_modules_integration" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;347;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.compiler_splitter" "D:/tinydbms/tinydbms/build-real/tests/tinydbms_compiler_splitter_test.exe")
set_tests_properties("tinydbms.compiler_splitter" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;359;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.compiler_lexer" "D:/tinydbms/tinydbms/build-real/tests/tinydbms_compiler_lexer_test.exe")
set_tests_properties("tinydbms.compiler_lexer" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;374;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.compiler_parser_create" "D:/tinydbms/tinydbms/build-real/tests/tinydbms_compiler_parser_create_test.exe")
set_tests_properties("tinydbms.compiler_parser_create" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;389;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.compiler_parser_insert" "D:/tinydbms/tinydbms/build-real/tests/tinydbms_compiler_parser_insert_test.exe")
set_tests_properties("tinydbms.compiler_parser_insert" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;404;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.compiler_parser_expression" "D:/tinydbms/tinydbms/build-real/tests/tinydbms_compiler_parser_expression_test.exe")
set_tests_properties("tinydbms.compiler_parser_expression" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;419;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.compiler_parser_select" "D:/tinydbms/tinydbms/build-real/tests/tinydbms_compiler_parser_select_test.exe")
set_tests_properties("tinydbms.compiler_parser_select" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;434;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.compiler_parser_delete" "D:/tinydbms/tinydbms/build-real/tests/tinydbms_compiler_parser_delete_test.exe")
set_tests_properties("tinydbms.compiler_parser_delete" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;449;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.compiler_semantic_create" "D:/tinydbms/tinydbms/build-real/tests/tinydbms_compiler_semantic_create_test.exe")
set_tests_properties("tinydbms.compiler_semantic_create" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;464;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.compiler_semantic_insert" "D:/tinydbms/tinydbms/build-real/tests/tinydbms_compiler_semantic_insert_test.exe")
set_tests_properties("tinydbms.compiler_semantic_insert" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;479;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.compiler_semantic_expression" "D:/tinydbms/tinydbms/build-real/tests/tinydbms_compiler_semantic_expression_test.exe")
set_tests_properties("tinydbms.compiler_semantic_expression" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;494;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.compiler_semantic_select" "D:/tinydbms/tinydbms/build-real/tests/tinydbms_compiler_semantic_select_test.exe")
set_tests_properties("tinydbms.compiler_semantic_select" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;509;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.compiler_semantic_delete" "D:/tinydbms/tinydbms/build-real/tests/tinydbms_compiler_semantic_delete_test.exe")
set_tests_properties("tinydbms.compiler_semantic_delete" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;524;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.compiler_planner_create" "D:/tinydbms/tinydbms/build-real/tests/tinydbms_compiler_planner_create_test.exe")
set_tests_properties("tinydbms.compiler_planner_create" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;539;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.compiler_planner_insert" "D:/tinydbms/tinydbms/build-real/tests/tinydbms_compiler_planner_insert_test.exe")
set_tests_properties("tinydbms.compiler_planner_insert" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;554;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.compiler_planner_select" "D:/tinydbms/tinydbms/build-real/tests/tinydbms_compiler_planner_select_test.exe")
set_tests_properties("tinydbms.compiler_planner_select" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;569;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.compiler_planner_delete" "D:/tinydbms/tinydbms/build-real/tests/tinydbms_compiler_planner_delete_test.exe")
set_tests_properties("tinydbms.compiler_planner_delete" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;584;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.compiler_compile" "D:/tinydbms/tinydbms/build-real/tests/tinydbms_compiler_compile_test.exe")
set_tests_properties("tinydbms.compiler_compile" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;595;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.compiler_hardening" "D:/tinydbms/tinydbms/build-real/tests/tinydbms_compiler_hardening_test.exe")
set_tests_properties("tinydbms.compiler_hardening" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;606;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.compiler_optimizer" "D:/tinydbms/tinydbms/build-real/tests/tinydbms_compiler_optimizer_test.exe")
set_tests_properties("tinydbms.compiler_optimizer" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;621;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.compiler_plan_formatter" "D:/tinydbms/tinydbms/build-real/tests/tinydbms_compiler_plan_formatter_test.exe")
set_tests_properties("tinydbms.compiler_plan_formatter" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;636;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.compiler_fuzz_valid" "D:/tinydbms/tinydbms/build-real/tests/tinydbms_compiler_fuzz_valid_test.exe")
set_tests_properties("tinydbms.compiler_fuzz_valid" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;651;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
add_test("tinydbms.compiler_fuzz_invalid" "D:/tinydbms/tinydbms/build-real/tests/tinydbms_compiler_fuzz_invalid_test.exe")
set_tests_properties("tinydbms.compiler_fuzz_invalid" PROPERTIES  _BACKTRACE_TRIPLES "D:/tinydbms/tinydbms/tests/CMakeLists.txt;666;add_test;D:/tinydbms/tinydbms/tests/CMakeLists.txt;0;")
